default: &default
  adapter: postgresql
  encoding: unicode
  host: localhost
  port: 5432
  timeout: 5000
  username: postgres
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: posts_development

test:
  <<: *default
  database: posts_test

production:
  primary: &primary_production
    <<: *default
    database: posts_production
    username: posts
    password: <%= ENV["POSTS_DATABASE_PASSWORD"] %>
  cache:
    <<: *primary_production
    database: posts_production_cache
    migrations_paths: db/cache_migrate
  queue:
    <<: *primary_production
    database: posts_production_queue
    migrations_paths: db/queue_migrate
  cable:
    <<: *primary_production
    database: posts_production_cable
    migrations_paths: db/cable_migrate
